---

- name: Install packages
  ansible.builtin.package:
    name: "{{ ( manage_basic_packages_install | default([]) ) + ( manage_basic_packages_install_other | default([]) ) }}"
    state: present
  when: ( manage_basic_packages_install or manage_basic_packages_install_other is defined )

- name: Remove packages
  ansible.builtin.package:
    name: "{{ ( manage_basic_packages_install | default([]) ) + ( manage_basic_packages_install_other | default([]) ) }}"
    state: absent
  when: ( manage_basic_packages_remove or manage_basic_packages_remove_other is defined )
